_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/SSFR_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/SSFR_reader.yml',
]

weights: output/SSFR_r101_fpn_mstrain_2x_coco/model_final
find_unused_parameters: True
log_iter: 100
use_ema: true
ema_decay: 0.9998

#EvalDataset:
#  !COCODataSet
#  image_dir: test2017
#  anno_path: annotations/image_info_test-dev2017.json
#  dataset_dir: D:\PaddleDetection-develop\dataset\coco\ms coco

#save_prediction_only: True


#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet101_vd_pretrained.pdparams
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet101_pretrained.pdparams

ResNet:
  depth: 101
  variant: b
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4

epoch: 24
#2*
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.001
    steps: 500

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomFlip: {prob: 0.5}
    - RandomResize: {target_size: [[480, 1333], [512, 1333], [544, 1333], [576, 1333], [608, 1333], [640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 1}
    - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
    - PadGT: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: true
  use_shared_memory: true

